### ISSUE TITLE
Cant find valid ICU

### ISSUE THREAD

**Issue by alvitawa** [fedarovich/qbittorrent-cli#62]
I started getting this error recently when running `qbt`:

```
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication..ctor(McMaster.Extensions.CommandLineUtils.CommandLineApplication, McMaster.Extensions.CommandLineUtils.HelpText.IHelpTextGenerator, McMaster.Extensions.CommandLineUtils.Abstractions.CommandLineContext, Boolean)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication..ctor(Boolean)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor(Boolean)
   at QBittorrent.CommandLineInterface.Program.Main(System.String[])
Aborted (core dumped)
```

I'm on arch linux and have ICU installed. But it doesn't seem to be actually necessary because I can run

```
export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1; qbt
```

instead. This turns it off according to

https://stackoverflow.com/questions/59119904/process-terminated-couldnt-find-a-valid-icu-package-installed-on-the-system-in

**Comment by fedarovich** [comment]
Well, I'm not the maintainer of Arch build, so I cannot really help here. 

Using DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 is valid workaround.
